version: '3.9'
services:
  PasteMystBot:
    container_name: PasteMystBot
    build: .
    volumes:
      - type: bind
        source: ./PasteMystBot/bin/Debug/net6.0/logs
        target: /app/logs
      - type: bind
        source: ./PasteMystBot/bin/Debug/net6.0/data
        target: /app/data
    restart: always
    env_file:
      - .env
